package Java;

public class Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
//		try
//		{
//			int a=4/0;
//		}
////		catch(ArithmeticException e)
////		{
////			System.out.println(e.getMessage());
////		}
////		
//		catch(Exception df)
//		{
//			System.out.println("Something went wrong.");
//		}

		
		


